# Generated by Django 4.0.6 on 2022-09-07 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenses',
            name='exp_value',
        ),
    ]
