# Generated by Django 4.0.6 on 2022-09-07 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_remove_expenses_exp_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='exp_value',
            field=models.FloatField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
