# Generated by Django 4.0.6 on 2022-09-07 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_expenses_exp_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenses',
            name='exp_value',
        ),
        migrations.AddField(
            model_name='expenses',
            name='expvalue',
            field=models.IntegerField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
